export const AuditModules = {
  AUDIT_LOGS: 'audit-logging',
  GOVERNANCE_APPROVALS: 'governance/approvals',
  GOVERNANCE_REGISTRIES: 'governance/registries',
  GOVERNANCE_REGULATORY_GATES: 'governance/regulatory-gates',
  RISK_DECISION_RECORDS: 'risk-engine/risk-decision-records',
  AUTH: 'identity/auth',
  ACCESS_CONTROL: 'identity/access-control',
  CUSTOMER_AUTH: 'identity/auth/customer',
  ONBOARDING: 'identity/onboarding',
  PAYINS: 'asset-treasury/payins',
  DEPOSIT_TRANSACTIONS: 'trading/deposit-transactions',
  SWAP_TRANSACTIONS: 'trading/swap-transactions',
  SWAP_QUOTES: 'trading/swap-quotes',
  PRICING_CENTER: 'trading/pricing-center',
  WITHDRAW_TRANSACTIONS: 'trading/withdraw-transactions',
  PAYOUTS: 'asset-treasury/payouts',
  SAFEGUARDING_RECONCILIATION: 'clearing-settle/safeguarding-reconciliation',
  INTERNAL_TRANSACTIONS: 'asset-treasury/internal-transactions',
  INTERNAL_FUNDS: 'asset-treasury/internal-funds',
  TRANSACTION_COMPLIANCE: 'risk-engine/transaction-compliance',
  ASSETS: 'asset-treasury/assets',
  LIQUIDITY_CONFIG: 'counterparty/liquidity-config',
  ACCT_EVENTS: 'accounting/acct-events',
  CLEARING_TEMPLATES: 'clearing-settle/clearing-templates',
  JOURNAL_HEADER_TEMPLATES: 'accounting/journal-header-templates',
  JOURNAL_LINE_TEMPLATES: 'accounting/journal-line-templates',
  CUSTOMER_SWAP_RATES: 'identity/customer-swap-rates',
  COA: 'accounting/coa',
  WALLETS: 'asset-treasury/wallets',
  CUSTOMERS: 'identity/customers',
  INBOUND_TRANSFER_SIGNALS: 'trading/inbound-transfer-signals',
  WITHDRAW_WORKFLOW: 'orchestrators/withdraw-workflow',
} as const;

export const AuditEntityTypes = {
  APPROVAL_CASE: 'APPROVAL_CASE',
  SHAREHOLDING_REGISTRY_VERSION: 'SHAREHOLDING_REGISTRY_VERSION',
  APPOINTMENT_RECORD: 'APPOINTMENT_RECORD',
  REGULATORY_GATE_ITEM: 'REGULATORY_GATE_ITEM',
  TRAINING_RECORD: 'TRAINING_RECORD',
  CONFLICT_DISCLOSURE: 'CONFLICT_DISCLOSURE',
  WIND_DOWN_MATERIAL: 'WIND_DOWN_MATERIAL',
  ONBOARDING: 'ONBOARDING',
  ACCESS_CONTROL: 'ACCESS_CONTROL',
  ADMIN_ROLE_CHANGE_REQUEST: 'ADMIN_ROLE_CHANGE_REQUEST',
  RISK_DECISION_RECORD: 'RISK_DECISION_RECORD',
  PAYIN: 'PAYIN',
  DEPOSIT_TRANSACTION: 'DEPOSIT_TRANSACTION',
  SWAP_TRANSACTION: 'SWAP_TRANSACTION',
  WITHDRAW_TRANSACTION: 'WITHDRAW_TRANSACTION',
  PAYOUT: 'PAYOUT',
  RECONCILIATION_BREAK: 'RECONCILIATION_BREAK',
  RECONCILIATION_WARNING: 'RECONCILIATION_WARNING',
  SAFEGUARDING_RUN: 'SAFEGUARDING_RUN',
  FIAT_STATEMENT_IMPORT: 'FIAT_STATEMENT_IMPORT',
  INTERNAL_TRANSACTION: 'INTERNAL_TRANSACTION',
  INTERNAL_FUND: 'INTERNAL_FUND',
  AUDIT_EVIDENCE_PACKAGE: 'AUDIT_EVIDENCE_PACKAGE',
  KYT_CASE: 'KYT_CASE',
  TRAVEL_RULE_CASE: 'TRAVEL_RULE_CASE',
  AUTH: 'AUTH',
  CONFIG: 'CONFIG',
  ASSET: 'ASSET',
  LIQUIDITY_CONFIG: 'LIQUIDITY_CONFIG',
  ACCT_EVENT: 'ACCT_EVENT',
  CLEARING_TEMPLATE: 'CLEARING_TEMPLATE',
  JOURNAL_HEADER_TEMPLATE: 'JOURNAL_HEADER_TEMPLATE',
  JOURNAL_LINE_TEMPLATE: 'JOURNAL_LINE_TEMPLATE',
  CUSTOMER_SWAP_RATE: 'CUSTOMER_SWAP_RATE',
  COA: 'COA',
  WALLET: 'WALLET',
  WITHDRAWAL_ADDRESS: 'WITHDRAWAL_ADDRESS',
  CUSTOMER: 'CUSTOMER',
  INBOUND_TRANSFER_SIGNAL: 'INBOUND_TRANSFER_SIGNAL',
  SWAP_QUOTE: 'SWAP_QUOTE',
  PRICING_POLICY: 'PRICING_POLICY',
  WITHDRAW_PRICING_QUOTE: 'WITHDRAW_PRICING_QUOTE',
  ADMIN_USER: 'ADMIN_USER',
  PASSWORD_RESET_TOKEN: 'PASSWORD_RESET_TOKEN',
  APPROVAL_POLICY: 'APPROVAL_POLICY',
  TB_ACCOUNT: 'TB_ACCOUNT',
  TRANSACTION_LIMIT_POLICY: 'TRANSACTION_LIMIT_POLICY',
  WITHDRAWAL_FEE_LEVEL: 'WITHDRAWAL_FEE_LEVEL',
  WITHDRAWAL_FEE_LEVEL_CHANGE_REQUEST: 'WITHDRAWAL_FEE_LEVEL_CHANGE_REQUEST',
  WITHDRAWAL_FEE_LEVEL_BINDING: 'WITHDRAWAL_FEE_LEVEL_BINDING',
  SWAP_FEE_LEVEL: 'SWAP_FEE_LEVEL',
  SWAP_FEE_LEVEL_CHANGE_REQUEST: 'SWAP_FEE_LEVEL_CHANGE_REQUEST',
  SWAP_FEE_LEVEL_BINDING: 'SWAP_FEE_LEVEL_BINDING',
  INTERNAL_TRANSFER: 'INTERNAL_TRANSFER',
  SETTLEMENT_BATCH: 'SETTLEMENT_BATCH',
  OUTSTANDING: 'OUTSTANDING',
  FEE_ACCRUAL: 'FEE_ACCRUAL',
  RECONCILIATION_RUN_V8: 'RECONCILIATION_RUN_V8',
  RECONCILIATION_CASE: 'RECONCILIATION_CASE',
  RECONCILIATION_LINE_ITEM: 'RECONCILIATION_LINE_ITEM',
} as const;

export const AuditWorkflowTypes = {
  // Trading workflows
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  SWAP: 'SWAP',
  TRANSACTION: 'TRANSACTION',
  // Onboarding / compliance
  ONBOARDING: 'ONBOARDING',
  PERIODIC_REVIEW: 'PERIODIC_REVIEW',
  // Governance
  APPROVAL: 'APPROVAL',
  GOVERNANCE_REGISTRY: 'GOVERNANCE_REGISTRY',
  REGULATORY_GATE: 'REGULATORY_GATE',
  // Clearing & settlement
  SETTLEMENT: 'SETTLEMENT',
} as const;

export const AuditBusinessWorkflowTypes = {
  ADMIN_LOGIN_ACCESS: 'ADMIN_LOGIN_ACCESS',
  ADMIN_ROLE_BINDING_CHANGE: 'ADMIN_ROLE_BINDING_CHANGE',
  AUDIT_EVIDENCE_EXPORT: 'AUDIT_EVIDENCE_EXPORT',
  // Governance redesign workflow types (C1–D2)
  ADMIN_INVITE: 'ADMIN_INVITE',
  ADMIN_SUSPENSION: 'ADMIN_SUSPENSION',
  ADMIN_REACTIVATION: 'ADMIN_REACTIVATION',
  ADMIN_FIRST_LOGIN: 'ADMIN_FIRST_LOGIN',
  APPROVAL_POLICY: 'APPROVAL_POLICY',
  // Role Definition Governance (2026-05-08)
  ROLE_DEFINITION_CREATE: 'ROLE_DEFINITION_CREATE',
  ROLE_DEFINITION_MODIFY: 'ROLE_DEFINITION_MODIFY',
  // Credential Reset Governance (2026-05-10)
  ADMIN_PASSWORD_RESET: 'ADMIN_PASSWORD_RESET',
  ADMIN_MFA_RESET: 'ADMIN_MFA_RESET',
  // Custodian Wallet Create (2026-05-13)
  CUSTODIAN_WALLET_CREATE: 'CUSTODIAN_WALLET_CREATE',
  WITHDRAWAL_ADDRESS_REGISTRATION: 'WITHDRAWAL_ADDRESS_REGISTRATION',
  TB_ACCOUNT_MANUAL_CREATE: 'TB_ACCOUNT_MANUAL_CREATE',
  // Asset Suspension (2026-05-14)
  ASSET_SUSPENSION: 'ASSET_SUSPENSION',
  ASSET_REACTIVATION: 'ASSET_REACTIVATION',
  // Asset Creation & Activation (2026-05-14)
  ASSET_CREATION: 'ASSET_CREATION',
  ASSET_ACTIVATION: 'ASSET_ACTIVATION',
  // Transaction Limit Change (2026-05-16)
  TRANSACTION_LIMIT_CHANGE: 'TRANSACTION_LIMIT_CHANGE',
  // Transaction Limit Creation (2026-05-16)
  TRANSACTION_LIMIT_CREATION: 'TRANSACTION_LIMIT_CREATION',
  // Withdrawal Fee Level (2026-05-30)
  WITHDRAWAL_FEE_LEVEL_CREATION: 'WITHDRAWAL_FEE_LEVEL_CREATION',
  WITHDRAWAL_FEE_LEVEL_CHANGE: 'WITHDRAWAL_FEE_LEVEL_CHANGE',
  WITHDRAWAL_FEE_LEVEL_BINDING: 'WITHDRAWAL_FEE_LEVEL_BINDING',
  // Swap Fee Level (2026-05-31)
  SWAP_FEE_LEVEL_CREATION: 'SWAP_FEE_LEVEL_CREATION',
  SWAP_FEE_LEVEL_CHANGE: 'SWAP_FEE_LEVEL_CHANGE',
  SWAP_FEE_LEVEL_BINDING: 'SWAP_FEE_LEVEL_BINDING',
  // Trading Tier Upgrade (pre-registered, workflow deferred)
  TRADING_TIER_UPGRADE: 'TRADING_TIER_UPGRADE',
  // Withdraw Large-Value Approval Gate (2026-06-01)
  WITHDRAW_LARGE_VALUE_APPROVAL: 'WITHDRAW_LARGE_VALUE_APPROVAL',
  // Internal Transfer (V7, 2026-06-03)
  INTERNAL_TRANSFER: 'INTERNAL_TRANSFER',
  // V8 Reconciliation (2026-06-18)
  V8_RECONCILIATION: 'clearing-settle/reconciliation',
} as const;

export const AuditUserActions = {
  REQUEST_CREATED: 'REQUEST_CREATED',
  SUBMITTED: 'SUBMITTED',
  APPROVED_FOR_EXECUTION: 'APPROVED_FOR_EXECUTION',
  EXECUTED: 'EXECUTED',
  INVITATION_ISSUED: 'INVITATION_ISSUED',
  INVITATION_RESENT: 'INVITATION_RESENT',
  ACTIVATED: 'ACTIVATED',
  ACTIVATION_FAILED: 'ACTIVATION_FAILED',
  LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  ROLE_BINDINGS_UPDATED: 'ROLE_BINDINGS_UPDATED',
  CANCELLED: 'CANCELLED',
  EXPORTED: 'EXPORTED',
  EXPORT_FAILED: 'EXPORT_FAILED',
  DOWNLOADED: 'DOWNLOADED',
} as const;

export const AuditActions = {
  APPROVAL_SUBMITTED: 'APPROVAL_SUBMITTED',
  APPROVAL_APPROVED: 'APPROVAL_APPROVED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  APPROVAL_CANCELLED: 'APPROVAL_CANCELLED',
  APPROVAL_EXPIRED: 'APPROVAL_EXPIRED',
  APPROVAL_EXECUTED: 'APPROVAL_EXECUTED',
  APPROVAL_EXECUTION_FAILED: 'APPROVAL_EXECUTION_FAILED',
  APPROVAL_REQUIRED_MISSING: 'APPROVAL_REQUIRED_MISSING',
  SHAREHOLDING_REGISTRY_CREATED: 'SHAREHOLDING_REGISTRY_CREATED',
  SHAREHOLDING_REGISTRY_UPDATED: 'SHAREHOLDING_REGISTRY_UPDATED',
  APPOINTMENT_RECORD_CREATED: 'APPOINTMENT_RECORD_CREATED',
  APPOINTMENT_RECORD_UPDATED: 'APPOINTMENT_RECORD_UPDATED',
  REGULATORY_GATE_CREATED: 'REGULATORY_GATE_CREATED',
  REGULATORY_GATE_UPDATED: 'REGULATORY_GATE_UPDATED',
  REGULATORY_GATE_SUBMITTED: 'REGULATORY_GATE_SUBMITTED',
  REGULATORY_GATE_FEEDBACK_RECORDED: 'REGULATORY_GATE_FEEDBACK_RECORDED',
  REGULATORY_GATE_RECEIPT_BOUND: 'REGULATORY_GATE_RECEIPT_BOUND',
  REGULATORY_GATE_MARKED_EFFECTIVE: 'REGULATORY_GATE_MARKED_EFFECTIVE',
  REGULATORY_GATE_REVOKED: 'REGULATORY_GATE_REVOKED',
  TRAINING_RECORD_CREATED: 'TRAINING_RECORD_CREATED',
  TRAINING_RECORD_UPDATED: 'TRAINING_RECORD_UPDATED',
  CONFLICT_DISCLOSURE_CREATED: 'CONFLICT_DISCLOSURE_CREATED',
  CONFLICT_DISCLOSURE_UPDATED: 'CONFLICT_DISCLOSURE_UPDATED',
  WIND_DOWN_MATERIAL_CREATED: 'WIND_DOWN_MATERIAL_CREATED',
  WIND_DOWN_MATERIAL_UPDATED: 'WIND_DOWN_MATERIAL_UPDATED',
  DEPOSIT_CREATED: 'DEPOSIT_CREATED',
  DEPOSIT_COMPLIANCE_STARTED: 'DEPOSIT_COMPLIANCE_STARTED',
  DEPOSIT_GATE0_PASSED: 'DEPOSIT_GATE0_PASSED',
  DEPOSIT_KYT_APPLIED: 'DEPOSIT_KYT_APPLIED',
  DEPOSIT_TR_APPLIED: 'DEPOSIT_TR_APPLIED',
  DEPOSIT_APPROVED: 'DEPOSIT_APPROVED',
  DEPOSIT_COMPLETED: 'DEPOSIT_COMPLETED',
  DEPOSIT_COMPLIANCE_EVIDENCE_SYNCED: 'DEPOSIT_COMPLIANCE_EVIDENCE_SYNCED',
  DEPOSIT_ACCOUNTING_BLOCKED: 'DEPOSIT_ACCOUNTING_BLOCKED',
  CDD_SUBMITTED: 'CDD_SUBMITTED',
  CDD_APPROVED: 'CDD_APPROVED',
  EDD_REJECTED: 'EDD_REJECTED',
  FINAL_APPROVED: 'FINAL_APPROVED',
  CDD_SESSION_CREATED: 'CDD_SESSION_CREATED',
  CDD_SESSION_COMPLETED: 'CDD_SESSION_COMPLETED',
  EDD_SESSION_CREATED: 'EDD_SESSION_CREATED',
  EDD_SESSION_COMPLETED: 'EDD_SESSION_COMPLETED',
  ONBOARDING_WORKFLOW_CLEAR: 'ONBOARDING_WORKFLOW_CLEAR',
  ONBOARDING_WORKFLOW_REJECT: 'ONBOARDING_WORKFLOW_REJECT',
  ONBOARDING_WORKFLOW_REQUIRE_EDD: 'ONBOARDING_WORKFLOW_REQUIRE_EDD',
  PERIODIC_REVIEW_CYCLE_CREATED: 'PERIODIC_REVIEW_CYCLE_CREATED',
  PERIODIC_REVIEW_CDD_SUBMITTED: 'PERIODIC_REVIEW_CDD_SUBMITTED',
  PERIODIC_REVIEW_EDD_SUBMITTED: 'PERIODIC_REVIEW_EDD_SUBMITTED',
  PERIODIC_REVIEW_WORKFLOW_CLEAR: 'PERIODIC_REVIEW_WORKFLOW_CLEAR',
  PERIODIC_REVIEW_WORKFLOW_REJECT: 'PERIODIC_REVIEW_WORKFLOW_REJECT',
  PERIODIC_REVIEW_WORKFLOW_REQUIRE_EDD:
    'PERIODIC_REVIEW_WORKFLOW_REQUIRE_EDD',
  FINAL_APPROVAL_SUBMITTED: 'FINAL_APPROVAL_SUBMITTED',
  FINAL_APPROVAL_RESUBMITTED: 'FINAL_APPROVAL_RESUBMITTED',
  FINAL_APPROVAL_APPROVED: 'FINAL_APPROVAL_APPROVED',
  FINAL_APPROVAL_REJECTED: 'FINAL_APPROVAL_REJECTED',
  FINAL_APPROVAL_CANCELLED: 'FINAL_APPROVAL_CANCELLED',
  FINAL_APPROVAL_EXPIRED: 'FINAL_APPROVAL_EXPIRED',
  MANUAL_INVESTOR_CLASS_OVERRIDE: 'MANUAL_INVESTOR_CLASS_OVERRIDE',
  PAYIN_CREATED: 'PAYIN_CREATED',
  INBOUND_SIGNAL_SUBMITTED: 'INBOUND_SIGNAL_SUBMITTED',
  INBOUND_SIGNAL_SCANNED: 'INBOUND_SIGNAL_SCANNED',
  INBOUND_SIGNAL_MATCHED: 'INBOUND_SIGNAL_MATCHED',
  INBOUND_SIGNAL_BLOCKED: 'INBOUND_SIGNAL_BLOCKED',
  INBOUND_SIGNAL_FAILED: 'INBOUND_SIGNAL_FAILED',
  PAYIN_PENDING_TO_CONFIRMED: 'PAYIN_PENDING_TO_CONFIRMED',
  DEPOSIT_PAYIN_PENDING_TO_COMPLIANCE_PENDING:
    'DEPOSIT_PAYIN_PENDING_TO_COMPLIANCE_PENDING',
  DEPOSIT_COMPLIANCE_PENDING_TO_SUCCESS: 'DEPOSIT_COMPLIANCE_PENDING_TO_SUCCESS',
  SWAP_QUOTE_CREATED: 'SWAP_QUOTE_CREATED',
  SWAP_CREATED: 'SWAP_CREATED',
  SWAP_SUCCEEDED: 'SWAP_SUCCEEDED',
  SWAP_FAILED: 'SWAP_FAILED',
  SWAP_LEG_POSTED: 'SWAP_LEG_POSTED',
  SWAP_LEG_RETRIED: 'SWAP_LEG_RETRIED',
  SWAP_LEG_STUCK: 'SWAP_LEG_STUCK',
  SWAP_LEG_RESUMED: 'SWAP_LEG_RESUMED',
  SWAP_PRODUCT_RESTRICTED: 'SWAP_PRODUCT_RESTRICTED',
  SWAP_BEST_EXECUTION_EVIDENCE_EXPORTED: 'SWAP_BEST_EXECUTION_EVIDENCE_EXPORTED',
  WITHDRAW_CREATED: 'WITHDRAW_CREATED',
  WITHDRAW_CREATED_TO_PAYOUT_PENDING: 'WITHDRAW_CREATED_TO_PAYOUT_PENDING',
  WITHDRAW_PAYOUT_PENDING_TO_SUCCESS: 'WITHDRAW_PAYOUT_PENDING_TO_SUCCESS',
  PAYOUT_CREATED: 'PAYOUT_CREATED',
  PAYOUT_PENDING_TO_CLEAR: 'PAYOUT_PENDING_TO_CLEAR',
  WITHDRAW_FAILED_REVERSED: 'WITHDRAW_FAILED_REVERSED',
  // V5 Withdrawal Happy Path
  WITHDRAW_REQUESTED: 'WITHDRAW_REQUESTED',
  WITHDRAW_KYT_PHASE1_PASSED: 'WITHDRAW_KYT_PHASE1_PASSED',
  WITHDRAW_TRAVEL_RULE_PASSED: 'WITHDRAW_TRAVEL_RULE_PASSED',
  WITHDRAW_COMPLIANCE_PASSED: 'WITHDRAW_COMPLIANCE_PASSED',
  WITHDRAW_KYT_PHASE2_SUBMITTED: 'WITHDRAW_KYT_PHASE2_SUBMITTED',
  WITHDRAW_ACCOUNTING_POSTED: 'WITHDRAW_ACCOUNTING_POSTED',
  WITHDRAW_LOCK_RELEASED: 'WITHDRAW_LOCK_RELEASED',
  WITHDRAW_SUCCESS: 'WITHDRAW_SUCCESS',
  WITHDRAW_APPROVAL_REQUESTED: 'WITHDRAW_APPROVAL_REQUESTED',
  WITHDRAW_APPROVAL_GRANTED: 'WITHDRAW_APPROVAL_GRANTED',
  WITHDRAW_APPROVAL_DECLINED: 'WITHDRAW_APPROVAL_DECLINED',
  REIMBURSEMENT_OBLIGATION_OPENED: 'REIMBURSEMENT_OBLIGATION_OPENED',
  REIMBURSEMENT_OBLIGATION_REIMBURSED:
    'REIMBURSEMENT_OBLIGATION_REIMBURSED',
  REIMBURSEMENT_OBLIGATION_CANCELLED:
    'REIMBURSEMENT_OBLIGATION_CANCELLED',
  KYT_CASE_CREATED: 'KYT_CASE_CREATED',
  KYT_CASE_UPDATED: 'KYT_CASE_UPDATED',
  TRAVEL_RULE_UPDATED: 'TRAVEL_RULE_UPDATED',
  TX_RISK_EVALUATED: 'TX_RISK_EVALUATED',
  TX_ALERT_UPSERTED: 'TX_ALERT_UPSERTED',
  TX_DEPOSIT_FLAGGED: 'TX_DEPOSIT_FLAGGED',
  TX_DEPOSIT_RELEASED: 'TX_DEPOSIT_RELEASED',
  TX_DEPOSIT_FROZEN: 'TX_DEPOSIT_FROZEN',
  TX_DEPOSIT_REJECTED: 'TX_DEPOSIT_REJECTED',
  TX_DEPOSIT_RELEASE_BLOCKED: 'TX_DEPOSIT_RELEASE_BLOCKED',
  TX_SWAP_FLAGGED: 'TX_SWAP_FLAGGED',
  TX_SWAP_RELEASED: 'TX_SWAP_RELEASED',
  TX_SWAP_REJECTED: 'TX_SWAP_REJECTED',
  TX_SWAP_FAILED: 'TX_SWAP_FAILED',
  TX_WITHDRAW_FLAGGED: 'TX_WITHDRAW_FLAGGED',
  TX_WITHDRAW_RELEASED: 'TX_WITHDRAW_RELEASED',
  TX_WITHDRAW_REJECTED: 'TX_WITHDRAW_REJECTED',
  TX_WITHDRAW_RELEASE_BLOCKED: 'TX_WITHDRAW_RELEASE_BLOCKED',
  TX_WITHDRAW_FINAL_GATE_BLOCKED: 'TX_WITHDRAW_FINAL_GATE_BLOCKED',
  TX_RECONCILIATION_BREAK_DETECTED: 'TX_RECONCILIATION_BREAK_DETECTED',
  TX_RECONCILIATION_BREAK_RESOLVED: 'TX_RECONCILIATION_BREAK_RESOLVED',
  TX_SAFEGUARDING_BREAK_DETECTED: 'TX_SAFEGUARDING_BREAK_DETECTED',
  TX_SAFEGUARDING_BREAK_RESOLVED: 'TX_SAFEGUARDING_BREAK_RESOLVED',
  SAFEGUARDING_RUN_GENERATED: 'SAFEGUARDING_RUN_GENERATED',
  FIAT_STATEMENT_IMPORTED: 'FIAT_STATEMENT_IMPORTED',
  SAFEGUARDING_EVIDENCE_PACKAGE_EXPORTED:
    'SAFEGUARDING_EVIDENCE_PACKAGE_EXPORTED',
  WITHDRAW_EXTREME_VOLATILITY_BLOCKED: 'WITHDRAW_EXTREME_VOLATILITY_BLOCKED',
  RISK_DECISION_MANUAL_SIMULATED: 'MANUAL_RISK_DECISION_SIMULATED',
  ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
  ADMIN_LOGIN_FAILED: 'ADMIN_LOGIN_FAILED',
  CUSTOMER_LOGIN_SUCCESS: 'CUSTOMER_LOGIN_SUCCESS',
  CUSTOMER_LOGIN_FAILED: 'CUSTOMER_LOGIN_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  USER_ROLE_BINDING_UPDATED: 'USER_ROLE_BINDING_UPDATED',
  LP_CONFIG_UPDATED: 'LP_CONFIG_UPDATED',
  ACCT_EVENT_UPDATED: 'ACCT_EVENT_UPDATED',
  CLEARING_TEMPLATE_UPDATED: 'CLEARING_TEMPLATE_UPDATED',
  JOURNAL_TEMPLATE_UPDATED: 'JOURNAL_TEMPLATE_UPDATED',
  COA_CONFIG_UPDATED: 'COA_CONFIG_UPDATED',
  CUSTOMER_SWAP_RATE_UPDATED: 'CUSTOMER_SWAP_RATE_UPDATED',
  PRICING_POLICY_UPDATED: 'PRICING_POLICY_UPDATED',
  SWAP_PRICING_SIMULATED: 'SWAP_PRICING_SIMULATED',
  WITHDRAW_PRICING_SIMULATED: 'WITHDRAW_PRICING_SIMULATED',
  WITHDRAW_PRICING_QUOTE_CREATED: 'WITHDRAW_PRICING_QUOTE_CREATED',
  WITHDRAW_PRICING_QUOTE_CANCELLED: 'WITHDRAW_PRICING_QUOTE_CANCELLED',
  WITHDRAW_PRICING_QUOTE_USED: 'WITHDRAW_PRICING_QUOTE_USED',
  USER_CREATED: 'USER_CREATED',
  ADMIN_INVITATION_CREATED: 'ADMIN_INVITATION_CREATED',
  ADMIN_INVITATION_RESENT: 'ADMIN_INVITATION_RESENT',
  ADMIN_INVITATION_ACCEPTED: 'ADMIN_INVITATION_ACCEPTED',
  ADMIN_INVITATION_ACCEPT_FAILED: 'ADMIN_INVITATION_ACCEPT_FAILED',
  CUSTOMER_REGISTERED: 'CUSTOMER_REGISTERED',
  CUSTOMER_REGISTER_FAILED: 'CUSTOMER_REGISTER_FAILED',
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_FROZEN: 'CUSTOMER_FROZEN',
  CUSTOMER_UNFROZEN: 'CUSTOMER_UNFROZEN',
  CUSTOMER_DELETED: 'CUSTOMER_DELETED',
  WALLET_STATUS_UPDATED: 'WALLET_STATUS_UPDATED',
  DEPOSIT_WALLET_CREATED: 'DEPOSIT_WALLET_CREATED',
  DEPOSIT_WALLET_CREATE_FAILED: 'DEPOSIT_WALLET_CREATE_FAILED',
  SWAP_QUOTE_CANCELLED: 'SWAP_QUOTE_CANCELLED',
  SWAP_QUOTE_USED: 'SWAP_QUOTE_USED',
  SYSTEM_TX_COMPLIANCE_BACKFILL_EXECUTED:
    'SYSTEM_TX_COMPLIANCE_BACKFILL_EXECUTED',
  AUDIT_EVIDENCE_EXPORT_REQUESTED: 'AUDIT_EVIDENCE_EXPORT_REQUESTED',
  AUDIT_EVIDENCE_PACKAGE_EXPORTED: 'AUDIT_EVIDENCE_PACKAGE_EXPORTED',
  AUDIT_EVIDENCE_PACKAGE_DOWNLOADED: 'AUDIT_EVIDENCE_PACKAGE_DOWNLOADED',
  CASE_EVIDENCE_PACKAGE_EXPORTED: 'CASE_EVIDENCE_PACKAGE_EXPORTED',
  ALERT_TRIGGERED: 'ALERT_TRIGGERED',
  ALERT_ACKED: 'ALERT_ACKED',
  ALERT_ASSIGNED: 'ALERT_ASSIGNED',
  ALERT_ESCALATED: 'ALERT_ESCALATED',
  ALERT_OVERDUE_MARKED: 'ALERT_OVERDUE_MARKED',
  ALERT_RESOLVED: 'ALERT_RESOLVED',
  ALERT_FALSE_POSITIVE: 'ALERT_FALSE_POSITIVE',
  ALERT_REOPENED: 'ALERT_REOPENED',
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  INCIDENT_ASSIGNED: 'INCIDENT_ASSIGNED',
  INCIDENT_FROZEN: 'INCIDENT_FROZEN',
  INCIDENT_UNFROZEN: 'INCIDENT_UNFROZEN',
  INCIDENT_RESTRICTED: 'INCIDENT_RESTRICTED',
  INCIDENT_UNRESTRICTED: 'INCIDENT_UNRESTRICTED',
  INCIDENT_REPORTED: 'INCIDENT_REPORTED',
  INCIDENT_OVERDUE_MARKED: 'INCIDENT_OVERDUE_MARKED',
  INCIDENT_INVESTIGATION_STARTED: 'INCIDENT_INVESTIGATION_STARTED',
  INCIDENT_REPORT_DRAFT_SAVED: 'INCIDENT_REPORT_DRAFT_SAVED',
  INCIDENT_REPORT_FINALIZED: 'INCIDENT_REPORT_FINALIZED',
  INCIDENT_SUBMITTED_TO_MLRO: 'INCIDENT_SUBMITTED_TO_MLRO',
  INCIDENT_RETURNED_FOR_INVESTIGATION: 'INCIDENT_RETURNED_FOR_INVESTIGATION',
  INCIDENT_FINAL_DISPOSITION_APPROVED: 'INCIDENT_FINAL_DISPOSITION_APPROVED',
  INCIDENT_FILING_REQUIRED: 'INCIDENT_FILING_REQUIRED',
  INCIDENT_FILING_SUBMITTED: 'INCIDENT_FILING_SUBMITTED',
  INCIDENT_FILING_ACKNOWLEDGED: 'INCIDENT_FILING_ACKNOWLEDGED',
  INCIDENT_FILING_RETURNED: 'INCIDENT_FILING_RETURNED',
  INCIDENT_FILING_CLOSED: 'INCIDENT_FILING_CLOSED',
  INCIDENT_ALERT_LINKED: 'INCIDENT_ALERT_LINKED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  INCIDENT_CLOSED: 'INCIDENT_CLOSED',
  INCIDENT_FALSE_POSITIVE: 'INCIDENT_FALSE_POSITIVE',
  SYSTEM_WITHDRAW_CREATED_ORCHESTRATED: 'SYSTEM_WITHDRAW_CREATED_ORCHESTRATED',
  SYSTEM_WITHDRAW_TERMINAL_ORCHESTRATED: 'SYSTEM_WITHDRAW_TERMINAL_ORCHESTRATED',
  SYSTEM_WITHDRAW_APPROVED_ORCHESTRATED: 'SYSTEM_WITHDRAW_APPROVED_ORCHESTRATED',
  MANUAL_TB_ACCOUNT_CREATED: 'MANUAL_TB_ACCOUNT_CREATED',
  // Internal Transfer (V7, 2026-06-03)
  TRANSFER_WHITELIST_REJECTED: 'TRANSFER_WHITELIST_REJECTED',
  // Settlement Batch
  BATCH_CREATED: 'BATCH_CREATED',
  BATCH_SUCCEEDED: 'BATCH_SUCCEEDED',
  // Generic lifecycle verbs for Outstanding & FeeAccrual (entityType differentiates)
  CREATED: 'CREATED',
  LOCKED: 'LOCKED',
  SETTLED: 'SETTLED',
  // ───── Spec #4: INTERNAL_FUND/INTERNAL_TRANSFER short-name actions (CREATED reused from Spec #3)
  SIGNING: 'SIGNING',
  BROADCASTED: 'BROADCASTED',
  CONFIRMING: 'CONFIRMING',
  CONFIRMED: 'CONFIRMED',
  CLEARED: 'CLEARED',
  FAILED: 'FAILED',
  TIMED_OUT: 'TIMED_OUT',
  CANCELLED: 'CANCELLED',
  REORGED: 'REORGED',
  REQUESTED: 'REQUESTED',
  SUCCEEDED: 'SUCCEEDED',
  // V8 Reconciliation (2026-06-18)
  RECON_RUN_COMPLETED: 'RECON_RUN_COMPLETED',
  RECON_RUN_FAILED: 'RECON_RUN_FAILED',
  RECON_CASE_OPENED: 'RECON_CASE_OPENED',
  RECON_CASE_RECONFIRMED: 'RECON_CASE_RECONFIRMED',
  RECON_INVARIANT_BREAK: 'RECON_INVARIANT_BREAK',
} as const;

export const AuditGovernanceActions = {
  // Admin Login Access
  ADMIN_LOGIN_ACCESS: {
    LOGIN_SUCCESS:    'ADMIN_LOGIN_SUCCESS',
    LOGIN_FAILED:     'ADMIN_LOGIN_FAILED',
    ACCOUNT_LOCKED:   'ACCOUNT_LOCKED',
    ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  },

  // C1 — Admin Invite
  ADMIN_INVITE: {
    INVITE_REQUESTED:       'INVITE_REQUESTED',
    INVITE_LINK_DISPATCHED: 'INVITE_LINK_DISPATCHED',
    INVITE_CANCELLED:       'INVITE_CANCELLED',
    INVITE_LINK_EXPIRED:    'INVITE_LINK_EXPIRED',
    ACCOUNT_ACTIVATED:      'ACCOUNT_ACTIVATED',
  },

  // C2 — Admin Role Binding Change
  ADMIN_ROLE_BINDING_CHANGE: {
    CHANGE_REQUESTED:     'CHANGE_REQUESTED',
    CHANGE_APPLIED:       'CHANGE_APPLIED',
    CHANGE_APPLY_FAILED:  'CHANGE_APPLY_FAILED',
  },

  // C3a — Admin Suspension
  ADMIN_SUSPENSION: {
    SUSPENSION_REQUESTED: 'SUSPENSION_REQUESTED',
    ACCOUNT_SUSPENDED:    'ACCOUNT_SUSPENDED',
  },

  // C3b — Admin Reactivation
  ADMIN_REACTIVATION: {
    REACTIVATION_REQUESTED: 'REACTIVATION_REQUESTED',
    ACCOUNT_REACTIVATED:    'ACCOUNT_REACTIVATED',
  },

  // C4b — Approval Policy Modification
  APPROVAL_POLICY: {
    MODIFICATION_REQUESTED:    'MODIFICATION_REQUESTED',
    MODIFICATION_APPLIED:      'MODIFICATION_APPLIED',
    MODIFICATION_APPLY_FAILED: 'MODIFICATION_APPLY_FAILED',
  },

  // C5 — Audit Evidence Export
  AUDIT_EVIDENCE_EXPORT: {
    EXPORT_REQUESTED:     'EXPORT_REQUESTED',
    GENERATION_COMPLETED: 'GENERATION_COMPLETED',
    GENERATION_FAILED:    'GENERATION_FAILED',
    PACKAGE_DOWNLOADED:   'PACKAGE_DOWNLOADED',
  },

  // Credential Reset Governance (2026-05-10)
  ADMIN_PASSWORD_RESET: {
    RESET_REQUESTED:   'RESET_REQUESTED',
    RESET_EXECUTED:    'RESET_EXECUTED',
    RESET_FAILED:      'RESET_FAILED',
    RESET_CANCELLED:   'RESET_CANCELLED',
    // Self-service path (2026-05-19)
    SELF_RESET_REQUESTED:     'SELF_RESET_REQUESTED',
    SELF_RESET_TOKEN_CREATED: 'SELF_RESET_TOKEN_CREATED',
    SELF_RESET_COMPLETED:     'SELF_RESET_COMPLETED',
    RESET_CONSUMED:           'RESET_CONSUMED',
  },

  ADMIN_MFA_RESET: {
    RESET_REQUESTED:   'RESET_REQUESTED',
    RESET_EXECUTED:    'RESET_EXECUTED',
    RESET_FAILED:      'RESET_FAILED',
    RESET_CANCELLED:   'RESET_CANCELLED',
  },

  // C3c — Admin First Login
  ADMIN_FIRST_LOGIN: {
    IDENTITY_CONFIRMED:       'FIRST_LOGIN_IDENTITY_CONFIRMED',
    MFA_BINDING_INITIATED:    'FIRST_LOGIN_MFA_BINDING_INITIATED',
    MFA_VERIFY_FAILED:        'FIRST_LOGIN_MFA_VERIFY_FAILED',
    MFA_BINDING_COMPLETED:    'FIRST_LOGIN_MFA_BINDING_COMPLETED',
    FIRST_LOGIN_COMPLETED:    'FIRST_LOGIN_COMPLETED',
    MFA_VERIFY_LOCKED:        'FIRST_LOGIN_MFA_VERIFY_LOCKED',
    // Normal login (post-first-login)
    MFA_LOGIN_VERIFIED:       'MFA_LOGIN_VERIFIED',
    MFA_LOGIN_VERIFY_FAILED:  'MFA_LOGIN_VERIFY_FAILED',
  },

  // Role Definition Create (2026-05-08)
  ROLE_DEFINITION_CREATE: {
    CREATE_REQUESTED:     'CREATE_REQUESTED',
    ROLE_ACTIVATED:       'ROLE_ACTIVATED',
    ROLE_ACTIVATE_FAILED: 'ROLE_ACTIVATE_FAILED',
    CREATE_CANCELLED:     'CREATE_CANCELLED',
  },

  // Role Definition Modify (2026-05-08)
  ROLE_DEFINITION_MODIFY: {
    MODIFY_REQUESTED:     'MODIFY_REQUESTED',
    ROLE_MODIFIED:        'ROLE_MODIFIED',
    ROLE_MODIFY_FAILED:   'ROLE_MODIFY_FAILED',
    MODIFY_CANCELLED:     'MODIFY_CANCELLED',
  },

  // Custodian Wallet Create (2026-05-13)
  CUSTODIAN_WALLET_CREATE: {
    CREATE_REQUESTED:      'CREATE_REQUESTED',
    WALLET_CREATED:        'WALLET_CREATED',
    WALLET_CREATE_FAILED:  'WALLET_CREATE_FAILED',
    CREATE_CANCELLED:      'CREATE_CANCELLED',
  },

  // Withdrawal Address Registration (2026-05-13)
  WITHDRAWAL_ADDRESS_REGISTRATION: {
    ADDRESS_REGISTERED:   'ADDRESS_REGISTERED',
    ADDRESS_ACTIVATED:    'ADDRESS_ACTIVATED',
    ADDRESS_CANCELLED:    'ADDRESS_CANCELLED',
    ADDRESS_SUSPENDED:    'ADDRESS_SUSPENDED',
    MANUAL_COOLING_SKIP:  'MANUAL_COOLING_SKIP',
  },

  // Asset Suspension (2026-05-14)
  ASSET_SUSPENSION: {
    SUSPENSION_REQUESTED:          'SUSPENSION_REQUESTED',
    ASSET_SUSPENDED:               'ASSET_SUSPENDED',
    SUSPENSION_EXECUTION_FAILED:   'SUSPENSION_EXECUTION_FAILED',
  },

  // Asset Reactivation (2026-05-14)
  ASSET_REACTIVATION: {
    REACTIVATION_REQUESTED:          'REACTIVATION_REQUESTED',
    ASSET_REACTIVATED:               'ASSET_REACTIVATED',
    REACTIVATION_EXECUTION_FAILED:   'REACTIVATION_EXECUTION_FAILED',
  },

  // Asset Creation (2026-05-14) — no approval, direct create+provision
  ASSET_CREATION: {
    ASSET_CREATED_AND_PROVISIONED: 'ASSET_CREATED_AND_PROVISIONED',
    ASSET_CREATION_FAILED:         'ASSET_CREATION_FAILED',
    ASSET_PROVISIONING_UPDATED:    'ASSET_PROVISIONING_UPDATED',
  },

  // Asset Activation (2026-05-14) — replaces ASSET_LISTING activation
  ASSET_ACTIVATION: {
    ACTIVATION_REQUESTED:  'ACTIVATION_REQUESTED',
    ASSET_ACTIVATED:       'ASSET_ACTIVATED',
    ACTIVATION_FAILED:     'ACTIVATION_FAILED',
  },

  // Transaction Limit Change (2026-05-16)
  TRANSACTION_LIMIT_CHANGE: {
    CHANGE_REQUESTED:      'CHANGE_REQUESTED',
    CHANGE_APPLIED:        'CHANGE_APPLIED',
    CHANGE_APPLY_FAILED:   'CHANGE_APPLY_FAILED',
    CHANGE_CANCELLED:      'CHANGE_CANCELLED',
  },

  // Transaction Limit Creation (2026-05-16)
  TRANSACTION_LIMIT_CREATION: {
    CREATION_REQUESTED:     'CREATION_REQUESTED',
    CREATION_APPLIED:       'CREATION_APPLIED',
    CREATION_APPLY_FAILED:  'CREATION_APPLY_FAILED',
    CREATION_CANCELLED:     'CREATION_CANCELLED',
  },

  // Withdrawal Fee Level Creation (2026-05-30)
  WITHDRAWAL_FEE_LEVEL_CREATION: {
    CREATION_REQUESTED:    'CREATION_REQUESTED',
    CREATION_APPLIED:      'CREATION_APPLIED',
    CREATION_APPLY_FAILED: 'CREATION_APPLY_FAILED',
    CREATION_CANCELLED:    'CREATION_CANCELLED',
  },

  // Withdrawal Fee Level Change (2026-05-30)
  WITHDRAWAL_FEE_LEVEL_CHANGE: {
    CHANGE_REQUESTED:    'CHANGE_REQUESTED',
    CHANGE_APPLIED:      'CHANGE_APPLIED',
    CHANGE_APPLY_FAILED: 'CHANGE_APPLY_FAILED',
    CHANGE_CANCELLED:    'CHANGE_CANCELLED',
  },

  // Withdrawal Fee Level Binding (2026-05-30)
  WITHDRAWAL_FEE_LEVEL_BINDING: {
    LEVEL_BOUND:   'LEVEL_BOUND',
    LEVEL_UNBOUND: 'LEVEL_UNBOUND',
  },

  // Swap Fee Level Creation (2026-05-31)
  SWAP_FEE_LEVEL_CREATION: {
    CREATION_REQUESTED:    'CREATION_REQUESTED',
    CREATION_APPLIED:      'CREATION_APPLIED',
    CREATION_APPLY_FAILED: 'CREATION_APPLY_FAILED',
    CREATION_CANCELLED:    'CREATION_CANCELLED',
  },

  // Swap Fee Level Change (2026-05-31)
  SWAP_FEE_LEVEL_CHANGE: {
    CHANGE_REQUESTED:    'CHANGE_REQUESTED',
    CHANGE_APPLIED:      'CHANGE_APPLIED',
    CHANGE_APPLY_FAILED: 'CHANGE_APPLY_FAILED',
    CHANGE_CANCELLED:    'CHANGE_CANCELLED',
  },

  // Swap Fee Level Binding (2026-05-31)
  SWAP_FEE_LEVEL_BINDING: {
    LEVEL_BOUND:   'LEVEL_BOUND',
    LEVEL_UNBOUND: 'LEVEL_UNBOUND',
  },
} as const;

const AuditRawActionToUserActionMap = {
  [AuditActions.APPROVAL_SUBMITTED]: AuditUserActions.SUBMITTED,
  [AuditActions.APPROVAL_APPROVED]:
    AuditUserActions.APPROVED_FOR_EXECUTION,
  [AuditActions.APPROVAL_EXECUTED]: AuditUserActions.EXECUTED,
  [AuditActions.APPROVAL_EXECUTION_FAILED]: AuditUserActions.EXPORT_FAILED,
  [AuditActions.ADMIN_INVITATION_CREATED]:
    AuditUserActions.INVITATION_ISSUED,
  [AuditActions.ADMIN_INVITATION_RESENT]: AuditUserActions.INVITATION_RESENT,
  [AuditActions.ADMIN_INVITATION_ACCEPTED]: AuditUserActions.ACTIVATED,
  [AuditActions.ADMIN_INVITATION_ACCEPT_FAILED]:
    AuditUserActions.ACTIVATION_FAILED,
  [AuditActions.ADMIN_LOGIN_SUCCESS]: AuditUserActions.LOGIN_SUCCEEDED,
  [AuditActions.ADMIN_LOGIN_FAILED]: AuditUserActions.LOGIN_FAILED,
  [AuditActions.ACCOUNT_LOCKED]: AuditUserActions.ACCOUNT_LOCKED,
  [AuditActions.ACCOUNT_UNLOCKED]: AuditUserActions.ACCOUNT_UNLOCKED,
  [AuditActions.USER_CREATED]: AuditUserActions.EXECUTED,
  [AuditActions.USER_ROLE_BINDING_UPDATED]:
    AuditUserActions.ROLE_BINDINGS_UPDATED,
  [AuditActions.AUDIT_EVIDENCE_EXPORT_REQUESTED]:
    AuditUserActions.REQUEST_CREATED,
  [AuditActions.AUDIT_EVIDENCE_PACKAGE_EXPORTED]: AuditUserActions.EXPORTED,
  [AuditActions.AUDIT_EVIDENCE_PACKAGE_DOWNLOADED]:
    AuditUserActions.DOWNLOADED,
} as const;

function normalizePart(value: string): string {
  return String(value || '')
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase();
}

export function buildStateTransitionAction(
  entity: string,
  fromStatus: string,
  toStatus: string,
): string {
  const entityPart = normalizePart(entity);
  const fromPart = normalizePart(fromStatus);
  const toPart = normalizePart(toStatus);
  return `${entityPart}_${fromPart}_TO_${toPart}`;
}

export function mapRawAuditActionToUserAction(
  action: string,
): (typeof AuditUserActions)[keyof typeof AuditUserActions] | undefined {
  return AuditRawActionToUserActionMap[
    action as keyof typeof AuditRawActionToUserActionMap
  ];
}

// ───── Spec #4: INTERNAL_FUND state → short-name action mapping
const INTERNAL_FUND_STATE_TO_ACTION: Record<string, string> = {
  CREATED: 'CREATED',
  SIGNING: 'SIGNING',
  BROADCASTED: 'BROADCASTED',
  CONFIRMING: 'CONFIRMING',
  CONFIRMED: 'CONFIRMED',
  CLEAR: 'CLEARED',
  FAILED: 'FAILED',
  TIMEOUT: 'TIMED_OUT',
  CANCELLED: 'CANCELLED',
  RETURNED: 'REORGED',
};

/**
 * Map INTERNAL_FUND state-machine target status to a short verb-past audit action.
 * Falls back to UPPERCASE status string for any unmapped value (forward-compat).
 */
export function buildInternalFundStateAction(nextStatus: string): string {
  return (
    INTERNAL_FUND_STATE_TO_ACTION[nextStatus] ?? nextStatus.toUpperCase()
  );
}
