ALTER TABLE "customer_main" ADD COLUMN "onboardingStatus" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "customer_main" ADD COLUMN "operatingStatus" TEXT NOT NULL DEFAULT 'INACTIVE';
ALTER TABLE "customer_main" ADD COLUMN "restrictionStatus" TEXT NOT NULL DEFAULT 'CLEAR';

UPDATE "customer_main"
SET
  "onboardingStatus" = CASE UPPER(COALESCE("publicStatus", 'NONE'))
    WHEN 'PENDING_CDD' THEN 'PENDING_CDD_INPUT'
    WHEN 'REVIEW_CDD' THEN 'CDD_UNDER_REVIEW'
    WHEN 'PENDING_EDD' THEN 'PENDING_EDD_INPUT'
    WHEN 'REVIEW_EDD' THEN 'EDD_UNDER_REVIEW'
    WHEN 'FINAL_APPROVAL' THEN 'FINAL_APPROVAL'
    WHEN 'ACTIVE' THEN 'APPROVED'
    WHEN 'REJECTED' THEN 'REJECTED'
    WHEN 'WITHDRAWN' THEN 'WITHDRAWN'
    ELSE 'NONE'
  END,
  "operatingStatus" = CASE UPPER(COALESCE("publicStatus", 'NONE'))
    WHEN 'ACTIVE' THEN 'ACTIVE'
    ELSE 'INACTIVE'
  END,
  "restrictionStatus" = 'CLEAR';
